const ADDITION='ADDITION';
const SUBTRACTION='SUBTRACTION';
const MULTIPLICATION='MULTIPLICATION';
const DIVISION='DIVISION';
const RESULT='RESULT';
const CLEAR='CLEAR';
const NUMBER='NUMBER';

module.exports = {ADDITION,SUBTRACTION,MULTIPLICATION,DIVISION,RESULT,CLEAR,NUMBER}